### ISSUE TITLE
Possible bug in Hann wavelet implementation

### ISSUE THREAD

**Issue by nshervt** [alelab-upenn/graph-scattering-transforms#2]
Hello, in the implementation of the Hann wavelet, the summation term at the end of the warped scaling function (eq. 13 from [Shuman et. al.](https://ieeexplore.ieee.org/abstract/document/7088640)) seems to be calculated for the last scale only. I think you should change 

https://github.com/alelab-upenn/graph-scattering-transforms/blob/ee268d2cd6e6422fe80c886ea6aeaa41a3803336/Modules/graphScattering.py#L217

to 

`sumPsiSquared += np.abs(psi) ** 2 `

**Comment by fgfgama** [comment]
Hello, nshervt!

Thanks for finding this out. I have corrected it, and uploaded a new version of graphScattering.py with this corrected and other sorrounding code (like fixing the value of eMax, and making sure that the np.sqrt() doesn't get negative values due to round-off errors).

Feel free to download this new file.

Thanks!

**Comment by nshervt** [comment]
You're welcome! I was going to point out `eMax = np.log(eMax)`, which you have already fixed.
